version: "3"
services:
  seeder:
    depends_on:
      - sso
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - '.sso_credentials.env'
    volumes:
      - ./seed_script.rb:/seed_script.rb:ro
  sso:
    image: jboss/keycloak
    env_file:
      - '.sso_credentials.env'
    ports:
      - "80:8080"
