version: "3"
services:
  seeder:
    depends_on:
      - sso
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - '.sso_credentials.env'
    volumes:
      - ./seed_script.rb:/seed_script.rb:ro
      - ./spec:/spec:ro
  sso:
    image: registry.access.redhat.com/redhat-sso-7/sso72-openshift
    env_file:
      - '.sso_credentials.env'
    ports:
      - "8080:8080"
    environment:
      - SSO_ADMIN_USERNAME=user
      - SSO_ADMIN_PASSWORD=password
      - JAVA_OPTS_APPEND=-Dkeycloak.profile=preview
